# Generated by Django 5.1.6 on 2025-02-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='./upload')),
                ('processed_file', models.FileField(upload_to='./processed')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'performer',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=50)),
                ('time', models.DateField()),
                ('film_url', models.URLField()),
                ('desc', models.TextField()),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_app.performer')),
                ('film_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_app.type')),
            ],
            options={
                'db_table': 'Film',
            },
        ),
    ]
